const std = @import("std");

const Property = enum {
    any,
    cr,
    lf,
    control,
    extend,
    zwj,
    regional_indicator,
    prepend,
    spacing_mark,
    l,
    v,
    t,
    lv,
    lvt,
    extended_pictographic,
};

const Range = struct {
    first: u21,
    last: u21,
    property: Property,
};

fn parseProperty(s: []const u8) ?Property {
    if (std.mem.eql(u8, s, "CR")) return .cr;
    if (std.mem.eql(u8, s, "LF")) return .lf;
    if (std.mem.eql(u8, s, "Control")) return .control;
    if (std.mem.eql(u8, s, "Extend")) return .extend;
    if (std.mem.eql(u8, s, "ZWJ")) return .zwj;
    if (std.mem.eql(u8, s, "Regional_Indicator")) return .regional_indicator;
    if (std.mem.eql(u8, s, "Prepend")) return .prepend;
    if (std.mem.eql(u8, s, "SpacingMark")) return .spacing_mark;
    if (std.mem.eql(u8, s, "L")) return .l;
    if (std.mem.eql(u8, s, "V")) return .v;
    if (std.mem.eql(u8, s, "T")) return .t;
    if (std.mem.eql(u8, s, "LV")) return .lv;
    if (std.mem.eql(u8, s, "LVT")) return .lvt;
    if (std.mem.eql(u8, s, "Extended_Pictographic")) return .extended_pictographic;
    return null;
}

fn parseRangesFromFile(
    path: []const u8,
    wanted_prop: ?Property, // null = parse all known properties from file
    ranges: *std.ArrayList(Range),
) !void {
    const file = try std.fs.cwd().openFile(path, .{});
    defer file.close();
    var buf_reader = std.io.bufferedReader(file.reader());
    var line_buf: [1024]u8 = undefined;

    while (true) {
        const line = buf_reader.reader().readUntilDelimiter(&line_buf, '\n') catch |err| switch (err) {
            error.EndOfStream => break,
            else => return err,
        };
        const trimmed = std.mem.trimRight(u8, line, &[_]u8{ '\r', ' ', '\t' });
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        const semi = std.mem.indexOf(u8, trimmed, ";") orelse continue;
        const cp_part = std.mem.trimRight(u8, trimmed[0..semi], &[_]u8{ ' ', '\t' });
        const rest = std.mem.trimLeft(u8, trimmed[semi + 1 ..], &[_]u8{ ' ', '\t' });

        // Extract property token (up to first space or '#')
        var prop_end: usize = 0;
        while (prop_end < rest.len and rest[prop_end] != ' ' and rest[prop_end] != '#') : (prop_end += 1) {}
        const prop_str = rest[0..prop_end];

        const property = parseProperty(prop_str) orelse continue;
        if (wanted_prop != null and property != wanted_prop.?) continue;

        var first: u21 = undefined;
        var last: u21 = undefined;
        if (std.mem.indexOf(u8, cp_part, "..")) |dot| {
            first = try std.fmt.parseInt(u21, cp_part[0..dot], 16);
            last = try std.fmt.parseInt(u21, cp_part[dot + 2 ..], 16);
        } else {
            first = try std.fmt.parseInt(u21, cp_part, 16);
            last = first;
        }

        try ranges.append(.{ .first = first, .last = last, .property = property });
    }
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var ranges = std.ArrayList(Range).init(allocator);
    defer ranges.deinit();

    // Parse all GBP properties from GraphemeBreakProperty.txt
    try parseRangesFromFile("data/GraphemeBreakProperty.txt", null, &ranges);

    // Parse Extended_Pictographic from emoji-data.txt
    try parseRangesFromFile("data/emoji-data.txt", .extended_pictographic, &ranges);

    // Sort by first codepoint
    std.mem.sort(Range, ranges.items, {}, struct {
        fn lessThan(_: void, a: Range, b: Range) bool {
            return a.first < b.first;
        }
    }.lessThan);

    // Write output
    const output = try std.fs.cwd().createFile("src/tables/grapheme_break.zig", .{});
    defer output.close();
    const writer = output.writer();

    try writer.writeAll(
        \\//! Grapheme cluster break property table — Unicode 16.0.
        \\//! Sources: GraphemeBreakProperty.txt + emoji-data.txt (Extended_Pictographic).
        \\//! Auto-generated by tools/gen_grapheme_break.zig. Do not edit.
        \\
        \\pub const Property = enum(u4) {
        \\    any = 0,
        \\    cr,
        \\    lf,
        \\    control,
        \\    extend,
        \\    zwj,
        \\    regional_indicator,
        \\    prepend,
        \\    spacing_mark,
        \\    l,
        \\    v,
        \\    t,
        \\    lv,
        \\    lvt,
        \\    extended_pictographic,
        \\};
        \\
        \\pub const Range = struct {
        \\    first: u21,
        \\    last: u21,
        \\    property: Property,
        \\};
        \\
        \\/// Sorted by first codepoint. Binary-searchable. Default property for unlisted codepoints is .any.
        \\pub const table = [_]Range{
        \\
    );

    for (ranges.items) |r| {
        try writer.print("    .{{ .first = 0x{X:0>4}, .last = 0x{X:0>4}, .property = .{s} }},\n", .{
            @as(u32, r.first),
            @as(u32, r.last),
            @tagName(r.property),
        });
    }

    try writer.writeAll(
        \\};
        \\
    );

    const stderr = std.io.getStdErr().writer();
    try stderr.print("Generated {d} grapheme break ranges\n", .{ranges.items.len});
}
