const std = @import("std");

const Range = struct {
    first: u21,
    last: u21,
};

const WidthCategory = enum {
    wide, // W
    fullwidth, // F
};

const CategorizedRange = struct {
    range: Range,
    category: WidthCategory,
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input = try std.fs.cwd().openFile("data/EastAsianWidth.txt", .{});
    defer input.close();

    var ranges = std.ArrayList(CategorizedRange).init(allocator);
    defer ranges.deinit();

    var buf_reader = std.io.bufferedReader(input.reader());
    var line_buf: [1024]u8 = undefined;

    while (true) {
        const line = buf_reader.reader().readUntilDelimiter(&line_buf, '\n') catch |err| switch (err) {
            error.EndOfStream => break,
            else => return err,
        };

        // Skip comments and empty lines
        const trimmed = std.mem.trimRight(u8, line, &[_]u8{ '\r', ' ', '\t' });
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        // Parse: "XXXX..YYYY ; Z" or "XXXX ; Z"
        const semi_idx = std.mem.indexOf(u8, trimmed, ";") orelse continue;
        const cp_part = std.mem.trimRight(u8, trimmed[0..semi_idx], &[_]u8{ ' ', '\t' });
        const prop_part = std.mem.trimLeft(u8, trimmed[semi_idx + 1 ..], &[_]u8{ ' ', '\t' });

        // Extract property letter(s) before any space/comment
        var prop_end: u32 = 0;
        while (prop_end < prop_part.len and prop_part[prop_end] != ' ' and prop_part[prop_end] != '#') : (prop_end += 1) {}
        const prop = std.mem.trimRight(u8, prop_part[0..prop_end], &[_]u8{ ' ', '\t' });

        // Only keep W and F
        const category: WidthCategory = if (std.mem.eql(u8, prop, "W"))
            .wide
        else if (std.mem.eql(u8, prop, "F"))
            .fullwidth
        else
            continue;

        // Parse codepoint or range
        var first: u21 = undefined;
        var last: u21 = undefined;

        if (std.mem.indexOf(u8, cp_part, "..")) |dot_idx| {
            first = try std.fmt.parseInt(u21, cp_part[0..dot_idx], 16);
            last = try std.fmt.parseInt(u21, cp_part[dot_idx + 2 ..], 16);
        } else {
            first = try std.fmt.parseInt(u21, cp_part, 16);
            last = first;
        }

        try ranges.append(.{ .range = .{ .first = first, .last = last }, .category = category });
    }

    // Sort by first codepoint
    std.mem.sort(CategorizedRange, ranges.items, {}, struct {
        fn lessThan(_: void, a: CategorizedRange, b: CategorizedRange) bool {
            return a.range.first < b.range.first;
        }
    }.lessThan);

    // Write output
    const output = try std.fs.cwd().createFile("src/tables/east_asian_width.zig", .{});
    defer output.close();
    const writer = output.writer();

    try writer.writeAll(
        \\//! East Asian Width property table — Unicode 16.0.
        \\//! Auto-generated by tools/gen_east_asian_width.zig. Do not edit.
        \\
        \\pub const Width = enum(u2) {
        \\    wide,
        \\    fullwidth,
        \\};
        \\
        \\pub const Range = struct {
        \\    first: u21,
        \\    last: u21,
        \\    width: Width,
        \\};
        \\
        \\/// Wide (W) and Fullwidth (F) codepoint ranges, sorted by first codepoint.
        \\pub const table = [_]Range{
        \\
    );

    for (ranges.items) |entry| {
        try writer.print("    .{{ .first = 0x{X:0>4}, .last = 0x{X:0>4}, .width = .{s} }},\n", .{
            @as(u32, entry.range.first),
            @as(u32, entry.range.last),
            @tagName(entry.category),
        });
    }

    try writer.writeAll(
        \\};
        \\
    );

    const stderr = std.io.getStdErr().writer();
    try stderr.print("Generated {d} ranges\n", .{ranges.items.len});
}
