const std = @import("std");

const Range = struct {
    first: u21,
    last: u21,
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var ranges = std.ArrayList(Range).init(allocator);
    defer ranges.deinit();

    // Parse DerivedGeneralCategory.txt for Mn (Nonspacing_Mark) and Me (Enclosing_Mark)
    const input = try std.fs.cwd().openFile("data/DerivedGeneralCategory.txt", .{});
    defer input.close();

    var buf_reader = std.io.bufferedReader(input.reader());
    var line_buf: [1024]u8 = undefined;

    while (true) {
        const line = buf_reader.reader().readUntilDelimiter(&line_buf, '\n') catch |err| switch (err) {
            error.EndOfStream => break,
            else => return err,
        };

        const trimmed = std.mem.trimRight(u8, line, &[_]u8{ '\r', ' ', '\t' });
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        const semi_idx = std.mem.indexOf(u8, trimmed, ";") orelse continue;
        const cp_part = std.mem.trimRight(u8, trimmed[0..semi_idx], &[_]u8{ ' ', '\t' });
        const prop_part = std.mem.trimLeft(u8, trimmed[semi_idx + 1 ..], &[_]u8{ ' ', '\t' });

        var prop_end: u32 = 0;
        while (prop_end < prop_part.len and prop_part[prop_end] != ' ' and prop_part[prop_end] != '#') : (prop_end += 1) {}
        const prop = std.mem.trimRight(u8, prop_part[0..prop_end], &[_]u8{ ' ', '\t' });

        // Mn = Nonspacing_Mark, Me = Enclosing_Mark
        if (!std.mem.eql(u8, prop, "Mn") and !std.mem.eql(u8, prop, "Me")) continue;

        var first: u21 = undefined;
        var last: u21 = undefined;

        if (std.mem.indexOf(u8, cp_part, "..")) |dot_idx| {
            first = try std.fmt.parseInt(u21, cp_part[0..dot_idx], 16);
            last = try std.fmt.parseInt(u21, cp_part[dot_idx + 2 ..], 16);
        } else {
            first = try std.fmt.parseInt(u21, cp_part, 16);
            last = first;
        }

        try ranges.append(.{ .first = first, .last = last });
    }

    // Add hard-coded zero-width characters not covered by Mn/Me
    const extra_ranges = [_]Range{
        .{ .first = 0x00AD, .last = 0x00AD }, // SOFT HYPHEN
        .{ .first = 0x200B, .last = 0x200F }, // ZWSP, ZWNJ, ZWJ, LRM, RLM
        .{ .first = 0x2028, .last = 0x202E }, // line/paragraph separators, bidi controls
        .{ .first = 0x2060, .last = 0x2069 }, // WJ, function application, invisible operators, bidi isolates
        .{ .first = 0x206A, .last = 0x206F }, // deprecated formatting characters
        .{ .first = 0xFEFF, .last = 0xFEFF }, // BOM / ZWNBSP
        .{ .first = 0xFFF9, .last = 0xFFFB }, // interlinear annotation anchors
        .{ .first = 0x13430, .last = 0x1345F }, // Egyptian hieroglyph format controls
        .{ .first = 0x1BCA0, .last = 0x1BCA3 }, // shorthand format controls
        .{ .first = 0x1D173, .last = 0x1D17A }, // musical symbol formatting
        .{ .first = 0xE0001, .last = 0xE0001 }, // language tag
        .{ .first = 0xE0020, .last = 0xE007F }, // tag characters
        .{ .first = 0xE0100, .last = 0xE01EF }, // variation selectors supplement
    };

    for (&extra_ranges) |r| {
        try ranges.append(r);
    }

    // Sort by first codepoint
    std.mem.sort(Range, ranges.items, {}, struct {
        fn lessThan(_: void, a: Range, b: Range) bool {
            return a.first < b.first;
        }
    }.lessThan);

    // Merge overlapping/adjacent ranges
    var merged = std.ArrayList(Range).init(allocator);
    defer merged.deinit();

    for (ranges.items) |r| {
        if (merged.items.len > 0) {
            const prev = &merged.items[merged.items.len - 1];
            // Merge if overlapping or adjacent (last+1 >= next first)
            if (r.first <= prev.last + 1) {
                prev.last = @max(prev.last, r.last);
                continue;
            }
        }
        try merged.append(r);
    }

    // Write output
    const output = try std.fs.cwd().createFile("src/tables/zero_width.zig", .{});
    defer output.close();
    const writer = output.writer();

    try writer.writeAll(
        \\//! Zero-width codepoint ranges — Unicode 16.0.
        \\//! Includes: Nonspacing_Mark (Mn), Enclosing_Mark (Me), and known
        \\//! zero-width format/control characters (ZWJ, ZWNJ, VS, soft hyphen, etc.)
        \\//! Auto-generated by tools/gen_zero_width.zig. Do not edit.
        \\
        \\pub const Range = struct {
        \\    first: u21,
        \\    last: u21,
        \\};
        \\
        \\/// Zero-width codepoint ranges, sorted by first codepoint. Binary-searchable.
        \\pub const table = [_]Range{
        \\
    );

    for (merged.items) |r| {
        try writer.print("    .{{ .first = 0x{X:0>4}, .last = 0x{X:0>4} }},\n", .{
            @as(u32, r.first),
            @as(u32, r.last),
        });
    }

    try writer.writeAll(
        \\};
        \\
    );

    const stderr = std.io.getStdErr().writer();
    try stderr.print("Generated {d} merged ranges (from {d} raw ranges)\n", .{ merged.items.len, ranges.items.len });
}
